### PR TITLE
Fix if the coordinates are larger than 1000 

### PR DESCRIPTION
**Pull request by lolipopshock**
[Temporary solution for now..] Show warning and fix the coordinates when necessary

### CODE REVIEW

**Comment by rauthur** [comment]
Can you explain why clipping is a fix? I ran into the max 1000 dim error when using a higher DPI. The "fix" in my case was to use a lower DPI. Is it even possible to use LayoutParser with larger DPI? Is that the constraint?

**Comment by lolipopshock** [comment]
> Can you explain why clipping is a fix? I ran into the max 1000 dim error when using a higher DPI. The "fix" in my case was to use a lower DPI. Is it even possible to use LayoutParser with larger DPI? Is that the constraint?

Yes I agree with you -- this is a bad strategy. For now it is used for some hot bug fixes (just want to get a commit/PR created for reference)..

**Comment by kyleclo** [comment]
First, since @yoganandc is the MMDA user who found this bug, we need to make sure @yoganandc approves this fix.    Without his approval, I'm hesitant to merge this.

Second, if lower DPI is a solution for this as @rauthur , we shouldn't merge this temp fix; just require lower DPI usage

**Comment by rauthur** [comment]
I was experimenting with Tesseract OCR which recommends a DPI of at least 150. I tried to use the same images with layout parser, ran into this error and changed the DPI back to 72. If @yoganandc doesn't have luck at 72 then it could just be a massive PDF (in terms of dimensions). I'm not sure what's appropriate in that case.

**Comment by rauthur** [comment]
@lolipopshock Do you have an outline of a fix that would be better in this case? Just want to get a rough idea of steps even if we don't change anything now.

**Comment by lolipopshock** [comment]
> @lolipopshock Do you have an outline of a fix that would be better in this case? Just want to get a rough idea of steps even if we don't change anything now.

Thanks for checking this, @rauthur ! Here is my plan:
1. In the future, we won't use absolute coordinates for modeling, and we'll normalize them to some ranges, which is specified by the models.
2. So for example, for a box coordinate (12,24,30,50), page_size (200, 200), and the box range specified in the model (by default is [0, 1000]), it will convert the box coordinate to [60, 120, 150, 250], and then send to the models. This will ensure correct values regardless of the used DPIs.

**Comment by lolipopshock** [comment]
Merge with the latest update from Kyle, as a reference for running eval

**Comment by lolipopshock** [comment]
Fixed in #77

**Pull request closed without merging**
